const option = [
  { label: 'Karur', value: 'Karur' },
  { label: 'Erode', value: 'Erode' },
  { label: 'Chennai', value: 'Chennai' },
  { label: 'Aranthangi', value: 'Aranthangi' },
  { label: 'Dindigul', value: 'Dindigul' },
  { label: 'Chengalpet', value: 'Chengalpet' },
  { label: 'Coimbatore', value: 'Coimbatore' },
  { label: 'Madurai', value: 'Madurai' },
  { label: 'Cuddalore', value: 'Cuddalore' },
  { label: 'Kanyakumari', value: 'Kanyakumari' },
  { label: 'Namakkal', value: 'Namakkal' },
  { label: 'Dharmapuri', value: 'Dharmapuri' },
  { label: 'Krishnagiri', value: 'Krishnagiri' },
  { label: 'Theni', value: 'Theni' },
  { label: 'Tiruppur', value: 'Tiruppur' },
  { label: 'Salem', value: 'Salem' },
  { label: 'Tirunelveli', value: 'Tirunelveli' },
  { label: 'Trichy', value: 'Trichy' },
  { label: 'Kanchipuram', value: 'Kanchipuram' },
  { label: 'Pudukkottai', value: 'Pudukkottai' },
  { label: 'Nagapattinam', value: 'Nagapattinam' },
  { label: 'Ramanathapuram', value: 'Ramanathapuram' },
  { label: 'Perambalur', value: 'Perambalur' },
  { label: 'Kallakurichi', value: 'Kallakurichi' },
  { label: 'Mayiladuthurai', value: 'Mayiladuthurai' },
  { label: 'Ranipet', value: 'Ranipet' },
  { label: 'Sivaganga', value: 'Sivaganga' },
  { label: 'Tenkasi', value: 'Tenkasi' },
  { label: 'Thanjavur', value: 'Thanjavur' },
  { label: 'Tirupattur', value: 'Tirupattur' },
  { label: 'Tiruvallur', value: 'Tiruvallur' },
  { label: 'Tiruvannamalai', value: 'Tiruvannamalai' },
  { label: 'Tiruvarur', value: 'Tiruvarur' },
  { label: 'Thoothukudi', value: 'Thoothukudi' },
  { label: 'Vellore', value: 'Vellore' },
  { label: 'Villupuram', value: 'Villupuram' },
  { label: 'Virudhunagar', value: 'Virudhunagar' }
];
const type = [
  { value: "ANY BUS", label: "ANY BUS" },
  { value: "Private", label: "PRIVATE" },
  { value: "SETC", label: "SETC" },
];
export { option, type };